/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesaralprog;

//LandingOwnerActivity
import java.awt.Color;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author King.
 */
public class LandingOwnerActivity extends javax.swing.JFrame {
    String username, password, authority;
    
    //database
    private Connection connection;
    private Statement statement;
    private ResultSet resultSet;
    private final Koneksi koneksi = new Koneksi();
    
    private final Object[] namaKolomProduk = {"No", "Nama Produk", "Jumlah Produk", "Harga Beli", "Harga Jual", "Benefit"};
        
    private final Object[] namaKolomKaryawan = {"No", "Nama Karyawan"};
    
    DefaultTableModel tabelModelProduk = new DefaultTableModel(namaKolomProduk, 0);
    DefaultTableModel tabelModelKaryawan = new DefaultTableModel(namaKolomKaryawan, 0);;
    /**
     * Creates new form LandingActivity
     * @param username
     * @param password
     * @param authority
     */
    public LandingOwnerActivity(String username, String password, String authority) {
        initComponents();
        this.username = username;
        this.password = password;
        this.authority = authority;
        lblUsername.setText(lblUsername.getText() + username);
        lbl_benefit.setVisible(true);

        showDataProduk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneNav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PaneNavAdvantage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PaneNavSeeAdmin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PaneNavLogout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PaneHeader = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lbl_benefit = new javax.swing.JLabel();
        PaneBackgroundContent = new javax.swing.JPanel();
        PaneAdvantage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        PaneSeeAdmin = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_karyawan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(43, 43, 40));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1008, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaneNav.setBackground(new java.awt.Color(12, 90, 59));
        PaneNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Warehouse.in");
        PaneNav.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        PaneNav.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, 240, 20));

        PaneNavAdvantage.setBackground(new java.awt.Color(12, 90, 59));
        PaneNavAdvantage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaneNavAdvantageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PaneNavAdvantageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PaneNavAdvantageMouseExited(evt);
            }
        });
        PaneNavAdvantage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Analisis Keuntungan");
        PaneNavAdvantage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/baseline_timeline_white_18dp.png"))); // NOI18N
        PaneNavAdvantage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PaneNav.add(PaneNavAdvantage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 70));

        PaneNavSeeAdmin.setBackground(new java.awt.Color(12, 90, 59));
        PaneNavSeeAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaneNavSeeAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PaneNavSeeAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PaneNavSeeAdminMouseExited(evt);
            }
        });
        PaneNavSeeAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Liat Karyawan");
        PaneNavSeeAdmin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/baseline_person_white_18dp.png"))); // NOI18N
        PaneNavSeeAdmin.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        PaneNav.add(PaneNavSeeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 70));

        PaneNavLogout.setBackground(new java.awt.Color(12, 90, 59));
        PaneNavLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaneNavLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PaneNavLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PaneNavLogoutMouseExited(evt);
            }
        });
        PaneNavLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/baseline_power_settings_new_white_18dp.png"))); // NOI18N
        PaneNavLogout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Keluar");
        PaneNavLogout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        PaneNav.add(PaneNavLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 310, 70));

        getContentPane().add(PaneNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 306, 680));

        PaneHeader.setBackground(new java.awt.Color(74, 232, 169));
        PaneHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Welcome, ");
        PaneHeader.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lbl_benefit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_benefit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_benefit.setText("Total Keuntungan Usaha anda : ");
        PaneHeader.add(lbl_benefit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        getContentPane().add(PaneHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 750, 140));

        PaneBackgroundContent.setBackground(new java.awt.Color(43, 43, 40));
        PaneBackgroundContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaneAdvantage.setBackground(new java.awt.Color(43, 43, 40));
        PaneAdvantage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tbl_data.setBackground(new java.awt.Color(43, 43, 40));
        tbl_data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_data.setForeground(new java.awt.Color(255, 255, 255));
        tbl_data.setFocusable(false);
        tbl_data.setGridColor(new java.awt.Color(43, 43, 40));
        tbl_data.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tbl_data.setOpaque(false);
        tbl_data.setSelectionBackground(new java.awt.Color(74, 232, 169));
        tbl_data.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbl_data);
        if (tbl_data.getColumnModel().getColumnCount() > 0) {
            tbl_data.getColumnModel().getColumn(0).setResizable(false);
            tbl_data.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbl_data.getColumnModel().getColumn(1).setResizable(false);
            tbl_data.getColumnModel().getColumn(1).setPreferredWidth(10);
            tbl_data.getColumnModel().getColumn(2).setResizable(false);
            tbl_data.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbl_data.getColumnModel().getColumn(3).setResizable(false);
            tbl_data.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbl_data.getColumnModel().getColumn(4).setResizable(false);
            tbl_data.getColumnModel().getColumn(4).setPreferredWidth(10);
            tbl_data.getColumnModel().getColumn(5).setResizable(false);
            tbl_data.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        PaneAdvantage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 630, 360));

        jButton1.setBackground(new java.awt.Color(74, 232, 169));
        jButton1.setText("Export To Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PaneAdvantage.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        PaneBackgroundContent.add(PaneAdvantage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 730, 490));

        PaneSeeAdmin.setBackground(new java.awt.Color(43, 43, 40));
        PaneSeeAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_karyawan.setBackground(new java.awt.Color(43, 43, 40));
        tbl_karyawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_karyawan.setForeground(new java.awt.Color(255, 255, 255));
        tbl_karyawan.setFocusable(false);
        tbl_karyawan.setGridColor(new java.awt.Color(43, 43, 40));
        tbl_karyawan.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tbl_karyawan.setSelectionBackground(new java.awt.Color(74, 232, 169));
        tbl_karyawan.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tbl_karyawan);

        PaneSeeAdmin.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 480, 260));

        PaneBackgroundContent.add(PaneSeeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 730, 490));

        getContentPane().add(PaneBackgroundContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 740, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaneNavAdvantageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavAdvantageMouseEntered
        PaneNavAdvantage.setBackground(new Color(6,45,29));
    }//GEN-LAST:event_PaneNavAdvantageMouseEntered

    private void PaneNavAdvantageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavAdvantageMouseExited
        PaneNavAdvantage.setBackground(new Color(12,90,59));
    }//GEN-LAST:event_PaneNavAdvantageMouseExited

    private void PaneNavSeeAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavSeeAdminMouseEntered
        PaneNavSeeAdmin.setBackground(new Color(6,45,29));
    }//GEN-LAST:event_PaneNavSeeAdminMouseEntered

    private void PaneNavSeeAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavSeeAdminMouseExited
        PaneNavSeeAdmin.setBackground(new Color(12,90,59));
    }//GEN-LAST:event_PaneNavSeeAdminMouseExited

    private void PaneNavLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavLogoutMouseEntered
        PaneNavLogout.setBackground(new Color(6,45,29));
    }//GEN-LAST:event_PaneNavLogoutMouseEntered

    private void PaneNavLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavLogoutMouseExited
        PaneNavLogout.setBackground(new Color(12,90,59));
    }//GEN-LAST:event_PaneNavLogoutMouseExited

    private void PaneNavLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavLogoutMouseClicked
        this.setVisible(false);
        LoginActivity login = new LoginActivity();
        login.setVisible(true);
    }//GEN-LAST:event_PaneNavLogoutMouseClicked

    private void PaneNavAdvantageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavAdvantageMouseClicked
        onPaneAdvantage();
        showDataProduk();
    }//GEN-LAST:event_PaneNavAdvantageMouseClicked

    private void PaneNavSeeAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneNavSeeAdminMouseClicked
        onPaneSeeAdmin();
        showDataKaryawan();
    }//GEN-LAST:event_PaneNavSeeAdminMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            connection = koneksi.getKoneksi();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM produk");
            
            XSSFWorkbook wb = new XSSFWorkbook();
            
            Sheet sheet = wb.createSheet();
            
            Row row = sheet.createRow(0);
            
            String[] headerCell = {"Nama Produk", "Jumlah Produk", "Harga Beli", "Harga Jual", "Benefit"};
            for(int i = 0; i < headerCell.length; i++) {
                Cell cell = row.createCell(i);
                cell.setCellValue(headerCell[i]);
            }
            
            int noUrut = 1;
            
            while(resultSet.next()) {
                Row contentRow = sheet.createRow(noUrut++);
                
                String[] valueRow = {
                    resultSet.getString("nama_product"),
                    resultSet.getString("jumlah_product"),
                    resultSet.getString("harga_jual"),
                    resultSet.getString("harga_beli"),
                    resultSet.getString("benefit")
                };
                for(int i = 0; i < valueRow.length; i++) {
                    Cell contentCell = contentRow.createCell(i);
                    contentCell.setCellValue(valueRow[i]);
                }
            }
            
            String pattern = "MM-dd-yyyy";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            String date = simpleDateFormat.format(new Date());
            
            FileOutputStream fileOut = new FileOutputStream("D:\\Kuliah\\SEMESTER 3\\Alprog\\tubes\\xlsx\\" + username + "_" + date + ".xlsx");
            
            wb.write(fileOut);
            
            fileOut.close();
        } catch (IOException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Maaf, Terjadi masalah", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void onPaneAdvantage() {
        PaneAdvantage.setVisible(true);
        PaneSeeAdmin.setVisible(false);
    }
    
    private void onPaneSeeAdmin() {
        PaneSeeAdmin.setVisible(true);
        PaneAdvantage.setVisible(false);
    }
    
    public void showDataProduk() {
        for(int i = tbl_data.getRowCount() - 1; i >= 0; i--) {
            tabelModelProduk.removeRow(i);
        }
        
        try {
            connection = koneksi.getKoneksi();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM produk");
            
            int noUrut = 1;
            
            while(resultSet.next()) {
                String[] row = {
                    Integer.toString(noUrut++), 
                    resultSet.getString("nama_product"),
                    resultSet.getString("jumlah_product"),
                    resultSet.getString("harga_jual"),
                    resultSet.getString("harga_beli"),
                    resultSet.getString("benefit")
                };
                
                tabelModelProduk.addRow(row);
            }
            
            tbl_data.setModel(tabelModelProduk);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Maaf, Tampil data tidak berhasil", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
        }
        
        lbl_benefit.setVisible(true);
        
        double benefit= 0;
        
        for (int j = 0; j  < tbl_data.getRowCount(); j++) {
            String temp = String.valueOf(tbl_data.getValueAt(j, 5));
            benefit += Double.parseDouble(temp);
        }
        
        if(lbl_benefit.getText().length() == 30) {
            lbl_benefit.setText(String.format("%s %s", lbl_benefit.getText(), indonesianCurrency(benefit)));
        }
    }
    
    public void showDataKaryawan() {
        for(int i = tbl_karyawan.getRowCount() - 1; i >= 0; i--) {
            tabelModelKaryawan.removeRow(i);
        }
        
        LoginActivity getData = new LoginActivity();
        String[][] listUser = getData.getUser();
        
        int noUrut = 1;
        
        for (String[] listUser1 : listUser) {
            if (listUser1[2].equals("employee")) {
                String[] row = {Integer.toString(noUrut++), listUser1[0]};
                tabelModelKaryawan.addRow(row);
            }
        }
        
        tbl_karyawan.setModel(tabelModelKaryawan);
        
        lbl_benefit.setVisible(false);
    }
    
    private String indonesianCurrency(double nominal) {
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        return kursIndonesia.format(nominal); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingOwnerActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingOwnerActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingOwnerActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingOwnerActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingOwnerActivity(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneAdvantage;
    private javax.swing.JPanel PaneBackgroundContent;
    private javax.swing.JPanel PaneHeader;
    private javax.swing.JPanel PaneNav;
    private javax.swing.JPanel PaneNavAdvantage;
    private javax.swing.JPanel PaneNavLogout;
    private javax.swing.JPanel PaneNavSeeAdmin;
    private javax.swing.JPanel PaneSeeAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbl_benefit;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTable tbl_karyawan;
    // End of variables declaration//GEN-END:variables
}
