/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesaralprog;

//LandingEmployeeActivity
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author King.
 */
public class LandingEmployeeActivity extends javax.swing.JFrame {
    String username, password, authority;
    
    private double tempEditHargaJual = 0;
    
    DefaultTableModel tabelModel;
    
    //database
    private Connection connection;
    private Statement statement;
    private ResultSet resultSet;
    private Koneksi koneksi = new Koneksi();
    /**
     * Creates new form LandingEmployeeActivity
     * @param username
     * @param password
     * @param authority
     */
    public LandingEmployeeActivity(String username, String password, String authority) {
        initComponents();
        onPaneAdvantage();
        this.username = username;
        this.password = password;
        this.authority = authority;
        lblUsername.setText(lblUsername.getText() + username);
        
        Object[] namaKolom = {"No", "Nama Produk", "Jumlah Produk", "Harga Beli", "Harga Jual"};
        tabelModel = new DefaultTableModel(namaKolom, 0);
        
        showData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneNav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelNav1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelNav2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelNav3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelNav4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelNav5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PaneHeader = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        PaneBackgroundContent = new javax.swing.JPanel();
        PaneEditData = new javax.swing.JPanel();
        lbl_nama1 = new javax.swing.JLabel();
        edt_search_nama_produk = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btn_cari_data = new javax.swing.JButton();
        PaneFormEditData = new javax.swing.JPanel();
        lbl_produk1 = new javax.swing.JLabel();
        lbl_harga_beli1 = new javax.swing.JLabel();
        lbl_harga_jual1 = new javax.swing.JLabel();
        edt_edit_jumlah_produk = new javax.swing.JTextField();
        edt_edit_harga_beli = new javax.swing.JTextField();
        edt_edit_harga_jual = new javax.swing.JLabel();
        btn_edit_data = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        PaneAdvantage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        PaneAddData = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_produk = new javax.swing.JLabel();
        lbl_harga_beli = new javax.swing.JLabel();
        lbl_harga_jual = new javax.swing.JLabel();
        edt_nama_produk = new javax.swing.JTextField();
        edt_jumlah_produk = new javax.swing.JTextField();
        edt_harga_beli = new javax.swing.JTextField();
        edt_harga_jual = new javax.swing.JLabel();
        btn_tambah_data = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        PaneDeleteData = new javax.swing.JPanel();
        lbl_nama2 = new javax.swing.JLabel();
        edt_search_nama_produk1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btn_cari_data_hapus = new javax.swing.JButton();
        PaneFormHapusData = new javax.swing.JPanel();
        lbl_produk2 = new javax.swing.JLabel();
        lbl_harga_beli2 = new javax.swing.JLabel();
        lbl_harga_jual2 = new javax.swing.JLabel();
        btn_delete_data = new javax.swing.JButton();
        lbl_hapus_jumlah_produk = new javax.swing.JLabel();
        lbl_hapus_harga_beli = new javax.swing.JLabel();
        lbl_hapus_harga_jual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaneNav.setBackground(new java.awt.Color(12, 90, 59));
        PaneNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Warehouse.in");
        PaneNav.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        PaneNav.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, 240, 20));

        jPanelNav1.setBackground(new java.awt.Color(12, 90, 59));
        jPanelNav1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNav1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNav1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNav1MouseExited(evt);
            }
        });
        jPanelNav1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lihat Barang");
        jPanelNav1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/baseline_local_shipping_white_18dp.png"))); // NOI18N
        jPanelNav1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PaneNav.add(jPanelNav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 70));

        jPanelNav2.setBackground(new java.awt.Color(12, 90, 59));
        jPanelNav2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNav2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNav2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNav2MouseExited(evt);
            }
        });
        jPanelNav2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tambah Barang");
        jPanelNav2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/baseline_add_white_18dp.png"))); // NOI18N
        jPanelNav2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        PaneNav.add(jPanelNav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 310, 70));

        jPanelNav3.setBackground(new java.awt.Color(12, 90, 59));
        jPanelNav3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNav3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNav3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNav3MouseExited(evt);
            }
        });
        jPanelNav3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Edit Barang");
        jPanelNav3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/baseline_create_white_18dp.png"))); // NOI18N
        jPanelNav3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        PaneNav.add(jPanelNav3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 310, 70));

        jPanelNav4.setBackground(new java.awt.Color(12, 90, 59));
        jPanelNav4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNav4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNav4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNav4MouseExited(evt);
            }
        });
        jPanelNav4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Hapus Barang");
        jPanelNav4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/baseline_delete_white_18dp.png"))); // NOI18N
        jPanelNav4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        PaneNav.add(jPanelNav4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 310, 70));

        jPanelNav5.setBackground(new java.awt.Color(12, 90, 59));
        jPanelNav5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelNav5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelNav5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelNav5MouseExited(evt);
            }
        });
        jPanelNav5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/baseline_power_settings_new_white_18dp.png"))); // NOI18N
        jPanelNav5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Keluar");
        jPanelNav5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        PaneNav.add(jPanelNav5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 310, 70));

        getContentPane().add(PaneNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 700));

        PaneHeader.setBackground(new java.awt.Color(74, 232, 169));
        PaneHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Welcome, ");
        PaneHeader.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(PaneHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 760, 140));

        PaneBackgroundContent.setBackground(new java.awt.Color(43, 43, 40));
        PaneBackgroundContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaneEditData.setBackground(new java.awt.Color(43, 43, 40));
        PaneEditData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nama1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nama1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_nama1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nama1.setText("Nama Produk");
        PaneEditData.add(lbl_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        edt_search_nama_produk.setBackground(new java.awt.Color(43, 43, 40));
        edt_search_nama_produk.setForeground(new java.awt.Color(255, 255, 255));
        edt_search_nama_produk.setBorder(null);
        PaneEditData.add(edt_search_nama_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 260, 30));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        PaneEditData.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 260, -1));

        btn_cari_data.setBackground(new java.awt.Color(74, 232, 169));
        btn_cari_data.setText("Cari Data");
        btn_cari_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_dataActionPerformed(evt);
            }
        });
        PaneEditData.add(btn_cari_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 120, -1));

        PaneFormEditData.setBackground(new java.awt.Color(43, 43, 40));
        PaneFormEditData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_produk1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_produk1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_produk1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_produk1.setText("Jumlah Produk");
        PaneFormEditData.add(lbl_produk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lbl_harga_beli1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_harga_beli1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_harga_beli1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_harga_beli1.setText("Harga Beli");
        PaneFormEditData.add(lbl_harga_beli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_harga_jual1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_harga_jual1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_harga_jual1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_harga_jual1.setText("Harga Jual");
        PaneFormEditData.add(lbl_harga_jual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        edt_edit_jumlah_produk.setBackground(new java.awt.Color(43, 43, 40));
        edt_edit_jumlah_produk.setForeground(new java.awt.Color(255, 255, 255));
        edt_edit_jumlah_produk.setBorder(null);
        PaneFormEditData.add(edt_edit_jumlah_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 390, 30));

        edt_edit_harga_beli.setBackground(new java.awt.Color(43, 43, 40));
        edt_edit_harga_beli.setForeground(new java.awt.Color(255, 255, 255));
        edt_edit_harga_beli.setBorder(null);
        edt_edit_harga_beli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edt_edit_harga_beliFocusLost(evt);
            }
        });
        edt_edit_harga_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_edit_harga_beliActionPerformed(evt);
            }
        });
        edt_edit_harga_beli.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edt_edit_harga_beliPropertyChange(evt);
            }
        });
        PaneFormEditData.add(edt_edit_harga_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 390, 30));

        edt_edit_harga_jual.setBackground(new java.awt.Color(0, 204, 0));
        edt_edit_harga_jual.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        edt_edit_harga_jual.setForeground(new java.awt.Color(0, 204, 0));
        edt_edit_harga_jual.setText("0");
        PaneFormEditData.add(edt_edit_harga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        btn_edit_data.setBackground(new java.awt.Color(74, 232, 169));
        btn_edit_data.setText("Edit Data");
        btn_edit_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_dataActionPerformed(evt);
            }
        });
        PaneFormEditData.add(btn_edit_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 560, 40));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        PaneFormEditData.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 390, -1));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        PaneFormEditData.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 390, -1));

        PaneEditData.add(PaneFormEditData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 630, 340));

        PaneBackgroundContent.add(PaneEditData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 750, 500));

        PaneAdvantage.setBackground(new java.awt.Color(43, 43, 40));
        PaneAdvantage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        tbl_data.setAutoCreateRowSorter(true);
        tbl_data.setBackground(new java.awt.Color(43, 43, 40));
        tbl_data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_data.setForeground(new java.awt.Color(255, 255, 255));
        tbl_data.setFocusable(false);
        tbl_data.setGridColor(new java.awt.Color(43, 43, 40));
        tbl_data.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tbl_data.setOpaque(false);
        tbl_data.setSelectionBackground(new java.awt.Color(74, 232, 169));
        tbl_data.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tbl_data);
        if (tbl_data.getColumnModel().getColumnCount() > 0) {
            tbl_data.getColumnModel().getColumn(0).setResizable(false);
            tbl_data.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbl_data.getColumnModel().getColumn(1).setResizable(false);
            tbl_data.getColumnModel().getColumn(1).setPreferredWidth(10);
            tbl_data.getColumnModel().getColumn(2).setResizable(false);
            tbl_data.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbl_data.getColumnModel().getColumn(3).setResizable(false);
            tbl_data.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbl_data.getColumnModel().getColumn(4).setResizable(false);
            tbl_data.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        PaneAdvantage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 630, 360));

        PaneBackgroundContent.add(PaneAdvantage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 770, 510));

        PaneAddData.setBackground(new java.awt.Color(43, 43, 40));
        PaneAddData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Masukkan Data Berikut");
        PaneAddData.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lbl_nama.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nama.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_nama.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nama.setText("Nama Produk");
        PaneAddData.add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        lbl_produk.setBackground(new java.awt.Color(255, 255, 255));
        lbl_produk.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_produk.setForeground(new java.awt.Color(255, 255, 255));
        lbl_produk.setText("Jumlah Produk");
        PaneAddData.add(lbl_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        lbl_harga_beli.setBackground(new java.awt.Color(255, 255, 255));
        lbl_harga_beli.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_harga_beli.setForeground(new java.awt.Color(255, 255, 255));
        lbl_harga_beli.setText("Harga Beli");
        PaneAddData.add(lbl_harga_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        lbl_harga_jual.setBackground(new java.awt.Color(255, 255, 255));
        lbl_harga_jual.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_harga_jual.setForeground(new java.awt.Color(255, 255, 255));
        lbl_harga_jual.setText("Harga Jual");
        PaneAddData.add(lbl_harga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        edt_nama_produk.setBackground(new java.awt.Color(43, 43, 40));
        edt_nama_produk.setForeground(new java.awt.Color(255, 255, 255));
        edt_nama_produk.setBorder(null);
        PaneAddData.add(edt_nama_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 125, 390, 30));

        edt_jumlah_produk.setBackground(new java.awt.Color(43, 43, 40));
        edt_jumlah_produk.setForeground(new java.awt.Color(255, 255, 255));
        edt_jumlah_produk.setBorder(null);
        PaneAddData.add(edt_jumlah_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 205, 390, 30));

        edt_harga_beli.setBackground(new java.awt.Color(43, 43, 40));
        edt_harga_beli.setForeground(new java.awt.Color(255, 255, 255));
        edt_harga_beli.setBorder(null);
        edt_harga_beli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edt_harga_beliFocusLost(evt);
            }
        });
        edt_harga_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_harga_beliActionPerformed(evt);
            }
        });
        edt_harga_beli.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                edt_harga_beliPropertyChange(evt);
            }
        });
        PaneAddData.add(edt_harga_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 285, 390, 30));

        edt_harga_jual.setBackground(new java.awt.Color(0, 204, 0));
        edt_harga_jual.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        edt_harga_jual.setForeground(new java.awt.Color(0, 204, 0));
        edt_harga_jual.setText("0");
        PaneAddData.add(edt_harga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        btn_tambah_data.setBackground(new java.awt.Color(74, 232, 169));
        btn_tambah_data.setText("Tambah Data");
        btn_tambah_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_dataActionPerformed(evt);
            }
        });
        PaneAddData.add(btn_tambah_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 560, 40));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        PaneAddData.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 390, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        PaneAddData.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 390, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        PaneAddData.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 390, -1));

        PaneBackgroundContent.add(PaneAddData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 760, 510));

        PaneDeleteData.setBackground(new java.awt.Color(43, 43, 40));
        PaneDeleteData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nama2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nama2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_nama2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nama2.setText("Nama Produk");
        PaneDeleteData.add(lbl_nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        edt_search_nama_produk1.setBackground(new java.awt.Color(43, 43, 40));
        edt_search_nama_produk1.setForeground(new java.awt.Color(255, 255, 255));
        edt_search_nama_produk1.setBorder(null);
        PaneDeleteData.add(edt_search_nama_produk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 260, 30));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        PaneDeleteData.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 260, -1));

        btn_cari_data_hapus.setBackground(new java.awt.Color(74, 232, 169));
        btn_cari_data_hapus.setText("Cari Data");
        btn_cari_data_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_data_hapusActionPerformed(evt);
            }
        });
        PaneDeleteData.add(btn_cari_data_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 120, -1));

        PaneFormHapusData.setBackground(new java.awt.Color(43, 43, 40));
        PaneFormHapusData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_produk2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_produk2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_produk2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_produk2.setText("Jumlah Produk");
        PaneFormHapusData.add(lbl_produk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lbl_harga_beli2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_harga_beli2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_harga_beli2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_harga_beli2.setText("Harga Beli");
        PaneFormHapusData.add(lbl_harga_beli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbl_harga_jual2.setBackground(new java.awt.Color(255, 255, 255));
        lbl_harga_jual2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_harga_jual2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_harga_jual2.setText("Harga Jual");
        PaneFormHapusData.add(lbl_harga_jual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btn_delete_data.setBackground(new java.awt.Color(74, 232, 169));
        btn_delete_data.setText("Hapus Data");
        btn_delete_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_dataActionPerformed(evt);
            }
        });
        PaneFormHapusData.add(btn_delete_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 560, 40));

        lbl_hapus_jumlah_produk.setBackground(new java.awt.Color(255, 0, 51));
        lbl_hapus_jumlah_produk.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_hapus_jumlah_produk.setForeground(new java.awt.Color(255, 0, 51));
        lbl_hapus_jumlah_produk.setText("0");
        PaneFormHapusData.add(lbl_hapus_jumlah_produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        lbl_hapus_harga_beli.setBackground(new java.awt.Color(255, 0, 51));
        lbl_hapus_harga_beli.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_hapus_harga_beli.setForeground(new java.awt.Color(255, 0, 51));
        lbl_hapus_harga_beli.setText("0");
        PaneFormHapusData.add(lbl_hapus_harga_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        lbl_hapus_harga_jual.setBackground(new java.awt.Color(255, 0, 51));
        lbl_hapus_harga_jual.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbl_hapus_harga_jual.setForeground(new java.awt.Color(255, 0, 51));
        lbl_hapus_harga_jual.setText("0");
        PaneFormHapusData.add(lbl_hapus_harga_jual, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        PaneDeleteData.add(PaneFormHapusData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 630, 340));

        PaneBackgroundContent.add(PaneDeleteData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 750, 500));

        getContentPane().add(PaneBackgroundContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 770, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelNav1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav1MouseEntered
        jPanelNav1.setBackground(new Color(6,45,29));
    }//GEN-LAST:event_jPanelNav1MouseEntered

    private void jPanelNav1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav1MouseExited
        jPanelNav1.setBackground(new Color(12,90,59));
    }//GEN-LAST:event_jPanelNav1MouseExited

    private void jPanelNav2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav2MouseEntered
        jPanelNav2.setBackground(new Color(6,45,29));
    }//GEN-LAST:event_jPanelNav2MouseEntered

    private void jPanelNav2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav2MouseExited
        jPanelNav2.setBackground(new Color(12,90,59));
    }//GEN-LAST:event_jPanelNav2MouseExited

    private void jPanelNav5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav5MouseEntered
        jPanelNav5.setBackground(new Color(6,45,29));
    }//GEN-LAST:event_jPanelNav5MouseEntered

    private void jPanelNav5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav5MouseExited
        jPanelNav5.setBackground(new Color(12,90,59));
    }//GEN-LAST:event_jPanelNav5MouseExited

    private void jPanelNav5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav5MouseClicked
        this.setVisible(false);
        LoginActivity login = new LoginActivity();
        login.setVisible(true);
    }//GEN-LAST:event_jPanelNav5MouseClicked

    private void jPanelNav1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav1MouseClicked
        onPaneAdvantage();
        showData();
    }//GEN-LAST:event_jPanelNav1MouseClicked

    private void jPanelNav2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav2MouseClicked
        onPaneAddData();
    }//GEN-LAST:event_jPanelNav2MouseClicked

    private void btn_tambah_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_dataActionPerformed
        String nama = edt_nama_produk.getText();
        String jumlah = edt_jumlah_produk.getText();
        String hargaBeli = edt_harga_beli.getText();
        
        if(nama.equals("") || jumlah.equals("") || hargaBeli.equals("")) {
            JOptionPane.showMessageDialog(null, "Tidak Boleh ada Data yang Kosong", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
        } else {
            double hargaJual = Integer.valueOf(edt_harga_beli.getText()) + (Integer.valueOf(edt_harga_beli.getText()) * 0.2);

            try {
                connection = koneksi.getKoneksi();
                statement = connection.createStatement();
                statement.execute("INSERT INTO produk VALUES(NULL,'" + nama + "','" + jumlah + "','" + hargaJual + "','" + hargaBeli + "','" + Integer.valueOf(edt_harga_beli.getText()) * 0.2 + "')");
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal Menambah Data" + e.getMessage(), "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_tambah_dataActionPerformed

    private void edt_harga_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_harga_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_harga_beliActionPerformed

    private void edt_harga_beliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edt_harga_beliPropertyChange
        
    }//GEN-LAST:event_edt_harga_beliPropertyChange

    private void edt_harga_beliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edt_harga_beliFocusLost
        double hargaJual = 0;
        if(edt_harga_beli.getText() != null) {
            try {
                hargaJual = Integer.valueOf(edt_harga_beli.getText()) + (Integer.valueOf(edt_harga_beli.getText()) * 0.2);
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Masukkan Angka", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            }
        }
        edt_harga_jual.setText(indonesianCurrency(hargaJual));
    }//GEN-LAST:event_edt_harga_beliFocusLost

    private void jPanelNav3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav3MouseClicked
        onPaneEditData();
        PaneFormEditData.setVisible(false);
    }//GEN-LAST:event_jPanelNav3MouseClicked

    private void jPanelNav3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav3MouseEntered
        jPanelNav3.setBackground(new Color(6,45,29));
    }//GEN-LAST:event_jPanelNav3MouseEntered

    private void jPanelNav3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav3MouseExited
        jPanelNav3.setBackground(new Color(12,90,59));
    }//GEN-LAST:event_jPanelNav3MouseExited

    private void jPanelNav4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav4MouseClicked
        onPaneDeleteData();
        PaneFormHapusData.setVisible(false);
    }//GEN-LAST:event_jPanelNav4MouseClicked

    private void jPanelNav4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav4MouseEntered
        jPanelNav4.setBackground(new Color(6,45,29));
    }//GEN-LAST:event_jPanelNav4MouseEntered

    private void jPanelNav4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelNav4MouseExited
        jPanelNav4.setBackground(new Color(12,90,59));
    }//GEN-LAST:event_jPanelNav4MouseExited

    private void edt_edit_harga_beliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edt_edit_harga_beliFocusLost
        double hargaJual = 0;
        if(edt_edit_harga_beli.getText() != null) {
            try {
                hargaJual = Integer.valueOf(edt_edit_harga_beli.getText()) + (Integer.valueOf(edt_edit_harga_beli.getText()) * 0.2);
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Masukkan Angka", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            }
        }
        edt_edit_harga_jual.setText(indonesianCurrency(hargaJual));
    }//GEN-LAST:event_edt_edit_harga_beliFocusLost

    private void edt_edit_harga_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_edit_harga_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_edit_harga_beliActionPerformed

    private void edt_edit_harga_beliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_edt_edit_harga_beliPropertyChange
        
    }//GEN-LAST:event_edt_edit_harga_beliPropertyChange

    private void btn_edit_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_dataActionPerformed
        try{    
            int benefit = (int) Math.round(tempEditHargaJual) - Integer.valueOf(edt_edit_harga_beli.getText());
            
            connection = koneksi.getKoneksi();
            PreparedStatement preparedStatement = connection.prepareStatement(String.format("UPDATE produk SET jumlah_product = %s, harga_jual = %s, harga_beli = %s, benefit = %s WHERE nama_product = '%s'", 
                    edt_edit_jumlah_produk.getText(),
                    tempEditHargaJual,
                    edt_edit_harga_beli.getText(),
                    benefit,
                    edt_search_nama_produk.getText()));
            preparedStatement.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil di Update", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Maaf, Update data tidak berhasil", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            
        }
        
        tempEditHargaJual = 0;
    }//GEN-LAST:event_btn_edit_dataActionPerformed

    private void btn_cari_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_dataActionPerformed
        try{
            connection = koneksi.getKoneksi();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM produk WHERE nama_product = '" + edt_search_nama_produk.getText() + "'");
            
            if(resultSet.first()) {
                PaneFormEditData.setVisible(true);
                
                edt_edit_jumlah_produk.setText(resultSet.getString("jumlah_product"));
                edt_edit_harga_beli.setText(resultSet.getString("harga_beli"));
                
                double hargaJual = 0;
                tempEditHargaJual = Integer.valueOf(edt_edit_harga_beli.getText()) + (Integer.valueOf(edt_edit_harga_beli.getText()) * 0.2);
                if(edt_edit_harga_beli.getText() != null) {
                    try {
                        hargaJual = Integer.valueOf(edt_edit_harga_beli.getText()) + (Integer.valueOf(edt_edit_harga_beli.getText()) * 0.2);
                    } catch(NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Masukkan Angka", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
                    }
                }
                
                edt_edit_harga_jual.setText(indonesianCurrency(hargaJual));
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, Data tidak ditemukan", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            }
            
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Maaf, pencarian tidak berhasil", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btn_cari_dataActionPerformed

    private void btn_cari_data_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_data_hapusActionPerformed
        try{
            connection = koneksi.getKoneksi();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM produk WHERE nama_product = '" + edt_search_nama_produk1.getText() + "'");
            
            if(resultSet.first()) {
                PaneFormHapusData.setVisible(true);
                
                lbl_hapus_jumlah_produk.setText(resultSet.getString("jumlah_product"));
                lbl_hapus_harga_beli.setText(indonesianCurrency(Double.valueOf(resultSet.getString("harga_beli"))));
                lbl_hapus_harga_jual.setText(indonesianCurrency(Double.valueOf(resultSet.getString("harga_jual"))));
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, Data tidak ditemukan", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            }
            
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Maaf, pencarian tidak berhasil", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btn_cari_data_hapusActionPerformed

    private void btn_delete_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_dataActionPerformed
       try{    
            connection = koneksi.getKoneksi();
            PreparedStatement preparedStatement = connection.prepareStatement(String.format("DELETE FROM produk WHERE nama_product = '%s'", 
                    edt_search_nama_produk1.getText()));
            preparedStatement.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Maaf, Update data tidak berhasil", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            
        }
       
       PaneFormHapusData.setVisible(false);
       edt_search_nama_produk1.setText("");
    }//GEN-LAST:event_btn_delete_dataActionPerformed
    
    public void showData() {
        for(int i = tbl_data.getRowCount() - 1; i >= 0; i--) {
            tabelModel.removeRow(i);
        }
        
        try {
            connection = koneksi.getKoneksi();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM produk");
            
            int noUrut = 1;
            
            while(resultSet.next()) {
                String[] row = {
                    Integer.toString(noUrut++), 
                    resultSet.getString("nama_product"),
                    resultSet.getString("jumlah_product"),
                    resultSet.getString("harga_beli"),
                    resultSet.getString("harga_jual")
                };
                
                tabelModel.addRow(row);
            }
            
            tbl_data.setModel(tabelModel);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Maaf, Tampil data tidak berhasil", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
        }
    }
    
    private String indonesianCurrency(double nominal) {
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        return kursIndonesia.format(nominal); 
    }
    
    private void onPaneAdvantage() {
        PaneAdvantage.setVisible(true);
        PaneAddData.setVisible(false);
        PaneEditData.setVisible(false);
        PaneDeleteData.setVisible(false);
    }
    
    private void onPaneAddData() {
        PaneAddData.setVisible(true);
        PaneAdvantage.setVisible(false);
        PaneEditData.setVisible(false);
        PaneDeleteData.setVisible(false);
    }
    
    private void onPaneEditData() {
        PaneEditData.setVisible(true);
        PaneAdvantage.setVisible(false);
        PaneAddData.setVisible(false);
        PaneDeleteData.setVisible(false);
    }
    
    private void onPaneDeleteData() {
        PaneDeleteData.setVisible(true);
        PaneAdvantage.setVisible(false);
        PaneAddData.setVisible(false);
        PaneEditData.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingEmployeeActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingEmployeeActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingEmployeeActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingEmployeeActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingEmployeeActivity(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneAddData;
    private javax.swing.JPanel PaneAdvantage;
    private javax.swing.JPanel PaneBackgroundContent;
    private javax.swing.JPanel PaneDeleteData;
    private javax.swing.JPanel PaneEditData;
    private javax.swing.JPanel PaneFormEditData;
    private javax.swing.JPanel PaneFormHapusData;
    private javax.swing.JPanel PaneHeader;
    private javax.swing.JPanel PaneNav;
    private javax.swing.JButton btn_cari_data;
    private javax.swing.JButton btn_cari_data_hapus;
    private javax.swing.JButton btn_delete_data;
    private javax.swing.JButton btn_edit_data;
    private javax.swing.JButton btn_tambah_data;
    private javax.swing.JTextField edt_edit_harga_beli;
    private javax.swing.JLabel edt_edit_harga_jual;
    private javax.swing.JTextField edt_edit_jumlah_produk;
    private javax.swing.JTextField edt_harga_beli;
    private javax.swing.JLabel edt_harga_jual;
    private javax.swing.JTextField edt_jumlah_produk;
    private javax.swing.JTextField edt_nama_produk;
    private javax.swing.JTextField edt_search_nama_produk;
    private javax.swing.JTextField edt_search_nama_produk1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelNav1;
    private javax.swing.JPanel jPanelNav2;
    private javax.swing.JPanel jPanelNav3;
    private javax.swing.JPanel jPanelNav4;
    private javax.swing.JPanel jPanelNav5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbl_hapus_harga_beli;
    private javax.swing.JLabel lbl_hapus_harga_jual;
    private javax.swing.JLabel lbl_hapus_jumlah_produk;
    private javax.swing.JLabel lbl_harga_beli;
    private javax.swing.JLabel lbl_harga_beli1;
    private javax.swing.JLabel lbl_harga_beli2;
    private javax.swing.JLabel lbl_harga_jual;
    private javax.swing.JLabel lbl_harga_jual1;
    private javax.swing.JLabel lbl_harga_jual2;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_nama1;
    private javax.swing.JLabel lbl_nama2;
    private javax.swing.JLabel lbl_produk;
    private javax.swing.JLabel lbl_produk1;
    private javax.swing.JLabel lbl_produk2;
    private javax.swing.JTable tbl_data;
    // End of variables declaration//GEN-END:variables
}
