/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesaralprog;

//LoginActivity
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author King.
 */
public class LoginActivity extends javax.swing.JFrame {
    
//    {"username", "password", "level"}
    private static String[][] user = {{"Si Boss", "1", "admin"},
        {"Jamal", "1", "employee"},
        {"Dobleh", "1", "employee"},
        {"Kabur", "1", "employee"},
        {"Alung", "1", "employee"}};
    
    public LoginActivity() {
        initComponents();
        lblIcon.setIcon(resizeImage("/tugasbesaralprog/image/warehouse.png", 200, 200));
    }
    
    public String[][] getUser() {
        return user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sepUsername = new javax.swing.JSeparator();
        tfPassword = new javax.swing.JPasswordField();
        sepPassword = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(74, 232, 169));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesaralprog/image/warehouse.png"))); // NOI18N
        jPanel1.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 200));

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Warehouse.in");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cepat. Handal. Terpercaya");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 506, 680));

        jPanel2.setBackground(new java.awt.Color(43, 43, 40));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Masuk");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Username");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        tfUsername.setBackground(new java.awt.Color(43, 43, 40));
        tfUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfUsername.setForeground(new java.awt.Color(255, 255, 255));
        tfUsername.setBorder(null);
        tfUsername.setCaretColor(new java.awt.Color(102, 102, 102));
        jPanel2.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 400, 40));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        btnLogin.setBackground(new java.awt.Color(74, 232, 169));
        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 400, 40));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Ada kendala saat proses masuk? hubungi admin");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        sepUsername.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(sepUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 400, -1));

        tfPassword.setBackground(new java.awt.Color(43, 43, 40));
        tfPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(255, 255, 255));
        tfPassword.setBorder(null);
        jPanel2.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 400, 40));

        sepPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(sepPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 400, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 530, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        String username = tfUsername.getText();
        String password = tfPassword.getText();
        String authority = null;
        
        boolean isExist = false;
        int atIndex = 0;
        
        for(int i = 0; i < user.length; i++) {
            if(user[i][0].equals(username)) {
                isExist = true;
                atIndex = i;
            }
        }
        
        if(isExist) {
            if(user[atIndex][1].equals(password)) {
                authority = user[atIndex][2];
                if(authority.equals("admin")) {
                    new LandingOwnerActivity(username, password, authority).setVisible(true);
                } else {
                    new LandingEmployeeActivity(username, password, authority).setVisible(true);
                }
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, Password anda salah", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
                tfPassword.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Maaf, Username anda tidak ditemukan", "Warehouse.in", JOptionPane.PLAIN_MESSAGE);
            tfUsername.setText("");
            tfPassword.setText("");
        }
        
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginActivity().setVisible(true);
            }
        });
    }
    
    private ImageIcon resizeImage(String path, int x, int y) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage();
        Image resizeImg = img.getScaledInstance(x, y, Image.SCALE_SMOOTH);
        ImageIcon finalIcon = new ImageIcon(resizeImg);
        return finalIcon;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JSeparator sepPassword;
    private javax.swing.JSeparator sepUsername;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
